# Generated by Django 4.2 on 2023-04-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
