# Generated by Django 4.2 on 2023-04-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_remove_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activation_email',
            new_name='activation_code',
        ),
    ]
