# Generated by Django 4.1 on 2023-05-01 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0003_alter_blog_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course_module.course'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
