# Generated by Django 4.1.2 on 2023-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('massage', models.TextField(verbose_name='متن تماس با ما')),
                ('response', models.CharField(max_length=300, verbose_name='پاسخ تماس با ما')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('is_read_by_admin', models.BooleanField(blank=True, null=True, verbose_name='خوانده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس ها با ما',
            },
        ),
    ]
