# Generated by Django 4.1 on 2023-04-25 18:29

from django.db import migrations, models
import student.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=11, validators=[student.validator.PhoneValidator()])),
                ('username', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
