# Generated by Django 4.2 on 2023-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=300, verbose_name='نام دوره')),
                ('price', models.IntegerField(verbose_name='قیمت دوره ')),
                ('short_description', models.CharField(db_index=True, max_length=150, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
                ('image', models.ImageField(null=True, upload_to='course_images', verbose_name='عکس دوره')),
            ],
        ),
    ]
